# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ja/Documents/NetworkTool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ja/Documents/NetworkTool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ja/Documents/NetworkTool/CMakeFiles /home/ja/Documents/NetworkTool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ja/Documents/NetworkTool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NetworkTool

# Build rule for target.
NetworkTool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NetworkTool
.PHONY : NetworkTool

# fast build rule for target.
NetworkTool/fast:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/build
.PHONY : NetworkTool/fast

Algorithm.o: Algorithm.cpp.o

.PHONY : Algorithm.o

# target to build an object file
Algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Algorithm.cpp.o
.PHONY : Algorithm.cpp.o

Algorithm.i: Algorithm.cpp.i

.PHONY : Algorithm.i

# target to preprocess a source file
Algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Algorithm.cpp.i
.PHONY : Algorithm.cpp.i

Algorithm.s: Algorithm.cpp.s

.PHONY : Algorithm.s

# target to generate assembly for a file
Algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Algorithm.cpp.s
.PHONY : Algorithm.cpp.s

DataBase.o: DataBase.cpp.o

.PHONY : DataBase.o

# target to build an object file
DataBase.cpp.o:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/DataBase.cpp.o
.PHONY : DataBase.cpp.o

DataBase.i: DataBase.cpp.i

.PHONY : DataBase.i

# target to preprocess a source file
DataBase.cpp.i:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/DataBase.cpp.i
.PHONY : DataBase.cpp.i

DataBase.s: DataBase.cpp.s

.PHONY : DataBase.s

# target to generate assembly for a file
DataBase.cpp.s:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/DataBase.cpp.s
.PHONY : DataBase.cpp.s

Host.o: Host.cpp.o

.PHONY : Host.o

# target to build an object file
Host.cpp.o:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Host.cpp.o
.PHONY : Host.cpp.o

Host.i: Host.cpp.i

.PHONY : Host.i

# target to preprocess a source file
Host.cpp.i:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Host.cpp.i
.PHONY : Host.cpp.i

Host.s: Host.cpp.s

.PHONY : Host.s

# target to generate assembly for a file
Host.cpp.s:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Host.cpp.s
.PHONY : Host.cpp.s

LinuxNotification.o: LinuxNotification.cpp.o

.PHONY : LinuxNotification.o

# target to build an object file
LinuxNotification.cpp.o:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/LinuxNotification.cpp.o
.PHONY : LinuxNotification.cpp.o

LinuxNotification.i: LinuxNotification.cpp.i

.PHONY : LinuxNotification.i

# target to preprocess a source file
LinuxNotification.cpp.i:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/LinuxNotification.cpp.i
.PHONY : LinuxNotification.cpp.i

LinuxNotification.s: LinuxNotification.cpp.s

.PHONY : LinuxNotification.s

# target to generate assembly for a file
LinuxNotification.cpp.s:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/LinuxNotification.cpp.s
.PHONY : LinuxNotification.cpp.s

Network.o: Network.cpp.o

.PHONY : Network.o

# target to build an object file
Network.cpp.o:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Network.cpp.o
.PHONY : Network.cpp.o

Network.i: Network.cpp.i

.PHONY : Network.i

# target to preprocess a source file
Network.cpp.i:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Network.cpp.i
.PHONY : Network.cpp.i

Network.s: Network.cpp.s

.PHONY : Network.s

# target to generate assembly for a file
Network.cpp.s:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Network.cpp.s
.PHONY : Network.cpp.s

Port.o: Port.cpp.o

.PHONY : Port.o

# target to build an object file
Port.cpp.o:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Port.cpp.o
.PHONY : Port.cpp.o

Port.i: Port.cpp.i

.PHONY : Port.i

# target to preprocess a source file
Port.cpp.i:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Port.cpp.i
.PHONY : Port.cpp.i

Port.s: Port.cpp.s

.PHONY : Port.s

# target to generate assembly for a file
Port.cpp.s:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/Port.cpp.s
.PHONY : Port.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... NetworkTool"
	@echo "... edit_cache"
	@echo "... Algorithm.o"
	@echo "... Algorithm.i"
	@echo "... Algorithm.s"
	@echo "... DataBase.o"
	@echo "... DataBase.i"
	@echo "... DataBase.s"
	@echo "... Host.o"
	@echo "... Host.i"
	@echo "... Host.s"
	@echo "... LinuxNotification.o"
	@echo "... LinuxNotification.i"
	@echo "... LinuxNotification.s"
	@echo "... Network.o"
	@echo "... Network.i"
	@echo "... Network.s"
	@echo "... Port.o"
	@echo "... Port.i"
	@echo "... Port.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

