# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ja/Documents/NetworkTool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ja/Documents/NetworkTool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ja/Documents/NetworkTool/CMakeFiles /home/ja/Documents/NetworkTool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ja/Documents/NetworkTool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NetworkTool

# Build rule for target.
NetworkTool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NetworkTool
.PHONY : NetworkTool

# fast build rule for target.
NetworkTool/fast:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/build
.PHONY : NetworkTool/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named NetworkToolTest

# Build rule for target.
NetworkToolTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NetworkToolTest
.PHONY : NetworkToolTest

# fast build rule for target.
NetworkToolTest/fast:
	$(MAKE) -f tests/CMakeFiles/NetworkToolTest.dir/build.make tests/CMakeFiles/NetworkToolTest.dir/build
.PHONY : NetworkToolTest/fast

src/source/Algorithm.o: src/source/Algorithm.cpp.o

.PHONY : src/source/Algorithm.o

# target to build an object file
src/source/Algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Algorithm.cpp.o
.PHONY : src/source/Algorithm.cpp.o

src/source/Algorithm.i: src/source/Algorithm.cpp.i

.PHONY : src/source/Algorithm.i

# target to preprocess a source file
src/source/Algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Algorithm.cpp.i
.PHONY : src/source/Algorithm.cpp.i

src/source/Algorithm.s: src/source/Algorithm.cpp.s

.PHONY : src/source/Algorithm.s

# target to generate assembly for a file
src/source/Algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Algorithm.cpp.s
.PHONY : src/source/Algorithm.cpp.s

src/source/DataBase.o: src/source/DataBase.cpp.o

.PHONY : src/source/DataBase.o

# target to build an object file
src/source/DataBase.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/DataBase.cpp.o
.PHONY : src/source/DataBase.cpp.o

src/source/DataBase.i: src/source/DataBase.cpp.i

.PHONY : src/source/DataBase.i

# target to preprocess a source file
src/source/DataBase.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/DataBase.cpp.i
.PHONY : src/source/DataBase.cpp.i

src/source/DataBase.s: src/source/DataBase.cpp.s

.PHONY : src/source/DataBase.s

# target to generate assembly for a file
src/source/DataBase.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/DataBase.cpp.s
.PHONY : src/source/DataBase.cpp.s

src/source/Host.o: src/source/Host.cpp.o

.PHONY : src/source/Host.o

# target to build an object file
src/source/Host.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Host.cpp.o
.PHONY : src/source/Host.cpp.o

src/source/Host.i: src/source/Host.cpp.i

.PHONY : src/source/Host.i

# target to preprocess a source file
src/source/Host.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Host.cpp.i
.PHONY : src/source/Host.cpp.i

src/source/Host.s: src/source/Host.cpp.s

.PHONY : src/source/Host.s

# target to generate assembly for a file
src/source/Host.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Host.cpp.s
.PHONY : src/source/Host.cpp.s

src/source/LinuxNotification.o: src/source/LinuxNotification.cpp.o

.PHONY : src/source/LinuxNotification.o

# target to build an object file
src/source/LinuxNotification.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/LinuxNotification.cpp.o
.PHONY : src/source/LinuxNotification.cpp.o

src/source/LinuxNotification.i: src/source/LinuxNotification.cpp.i

.PHONY : src/source/LinuxNotification.i

# target to preprocess a source file
src/source/LinuxNotification.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/LinuxNotification.cpp.i
.PHONY : src/source/LinuxNotification.cpp.i

src/source/LinuxNotification.s: src/source/LinuxNotification.cpp.s

.PHONY : src/source/LinuxNotification.s

# target to generate assembly for a file
src/source/LinuxNotification.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/LinuxNotification.cpp.s
.PHONY : src/source/LinuxNotification.cpp.s

src/source/Network.o: src/source/Network.cpp.o

.PHONY : src/source/Network.o

# target to build an object file
src/source/Network.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Network.cpp.o
.PHONY : src/source/Network.cpp.o

src/source/Network.i: src/source/Network.cpp.i

.PHONY : src/source/Network.i

# target to preprocess a source file
src/source/Network.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Network.cpp.i
.PHONY : src/source/Network.cpp.i

src/source/Network.s: src/source/Network.cpp.s

.PHONY : src/source/Network.s

# target to generate assembly for a file
src/source/Network.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Network.cpp.s
.PHONY : src/source/Network.cpp.s

src/source/Port.o: src/source/Port.cpp.o

.PHONY : src/source/Port.o

# target to build an object file
src/source/Port.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Port.cpp.o
.PHONY : src/source/Port.cpp.o

src/source/Port.i: src/source/Port.cpp.i

.PHONY : src/source/Port.i

# target to preprocess a source file
src/source/Port.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Port.cpp.i
.PHONY : src/source/Port.cpp.i

src/source/Port.s: src/source/Port.cpp.s

.PHONY : src/source/Port.s

# target to generate assembly for a file
src/source/Port.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/source/Port.cpp.s
.PHONY : src/source/Port.cpp.s

src/source/main.o: src/source/main.cpp.o

.PHONY : src/source/main.o

# target to build an object file
src/source/main.cpp.o:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/src/source/main.cpp.o
.PHONY : src/source/main.cpp.o

src/source/main.i: src/source/main.cpp.i

.PHONY : src/source/main.i

# target to preprocess a source file
src/source/main.cpp.i:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/src/source/main.cpp.i
.PHONY : src/source/main.cpp.i

src/source/main.s: src/source/main.cpp.s

.PHONY : src/source/main.s

# target to generate assembly for a file
src/source/main.cpp.s:
	$(MAKE) -f CMakeFiles/NetworkTool.dir/build.make CMakeFiles/NetworkTool.dir/src/source/main.cpp.s
.PHONY : src/source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... NetworkTool"
	@echo "... core"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... NetworkToolTest"
	@echo "... src/source/Algorithm.o"
	@echo "... src/source/Algorithm.i"
	@echo "... src/source/Algorithm.s"
	@echo "... src/source/DataBase.o"
	@echo "... src/source/DataBase.i"
	@echo "... src/source/DataBase.s"
	@echo "... src/source/Host.o"
	@echo "... src/source/Host.i"
	@echo "... src/source/Host.s"
	@echo "... src/source/LinuxNotification.o"
	@echo "... src/source/LinuxNotification.i"
	@echo "... src/source/LinuxNotification.s"
	@echo "... src/source/Network.o"
	@echo "... src/source/Network.i"
	@echo "... src/source/Network.s"
	@echo "... src/source/Port.o"
	@echo "... src/source/Port.i"
	@echo "... src/source/Port.s"
	@echo "... src/source/main.o"
	@echo "... src/source/main.i"
	@echo "... src/source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

